export type EventImpact = "critical" | "high" | "medium" | "low";
export type EventCategory =
  | "fomc"
  | "jobs"
  | "inflation"
  | "growth"
  | "earnings"
  | "policy"
  | "other";

export interface EconomicEvent {
  date: string; // YYYY-MM-DD
  title: string;
  description: string;
  impact: EventImpact;
  category: EventCategory;
  time?: string; // "08:30 ET" 형식
  isEstimate?: boolean; // 예상 날짜
}

export const IMPACT_COLORS: Record<EventImpact, string> = {
  critical: "#ef4444",
  high: "#f97316",
  medium: "#eab308",
  low: "#3b82f6",
};

export const IMPACT_BG: Record<EventImpact, string> = {
  critical: "bg-red-500",
  high: "bg-orange-500",
  medium: "bg-yellow-500",
  low: "bg-blue-500",
};

export const IMPACT_LABELS: Record<EventImpact, string> = {
  critical: "초고위험",
  high: "고위험",
  medium: "중위험",
  low: "저위험",
};

export const CATEGORY_LABELS: Record<EventCategory, string> = {
  fomc: "FOMC",
  jobs: "고용",
  inflation: "물가",
  growth: "성장",
  earnings: "실적",
  policy: "정책",
  other: "기타",
};

// ──────────────────────────────────────────────
// 2026 경제 이벤트 캘린더 (미국 기준)
// 날짜는 BLS/Fed 발표 기준, *표시는 추정
// ──────────────────────────────────────────────
export const ECONOMIC_EVENTS: EconomicEvent[] = [
  // ── FOMC 회의 (2026년 8회, 회의 종료일 기준) ──
  {
    date: "2026-01-28",
    title: "FOMC 금리 결정",
    description: "연방공개시장위원회 금리 결정 및 성명 발표. 기준금리 유지/인상/인하 방향 결정.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
  },
  {
    date: "2026-03-18",
    title: "FOMC 금리 결정 + SEP",
    description: "분기별 경제전망요약(SEP) 및 점도표 발표. 연간 기준금리 경로 제시.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
  },
  {
    date: "2026-04-29",
    title: "FOMC 금리 결정",
    description: "연방공개시장위원회 금리 결정 및 성명 발표.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-06-10",
    title: "FOMC 금리 결정 + SEP",
    description: "분기별 경제전망요약(SEP) 및 점도표 발표.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-29",
    title: "FOMC 금리 결정",
    description: "연방공개시장위원회 금리 결정 및 성명 발표.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-09-16",
    title: "FOMC 금리 결정 + SEP",
    description: "분기별 경제전망요약(SEP) 및 점도표 발표.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-10-28",
    title: "FOMC 금리 결정",
    description: "연방공개시장위원회 금리 결정 및 성명 발표.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-12-09",
    title: "FOMC 금리 결정 + SEP",
    description: "연말 분기별 경제전망요약(SEP) 및 점도표 발표.",
    impact: "critical",
    category: "fomc",
    time: "14:00 ET",
    isEstimate: true,
  },

  // ── CPI (소비자물가지수) ──
  {
    date: "2026-01-14",
    title: "CPI (12월)",
    description: "소비자물가지수 전년비·전월비 발표. 헤드라인 및 근원 CPI 포함.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-02-11",
    title: "CPI (1월)",
    description: "1월 소비자물가지수 발표. 새해 초 가격 책정 변화 주목.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-03-11",
    title: "CPI (2월)",
    description: "2월 소비자물가지수 발표.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-04-09",
    title: "CPI (3월)",
    description: "3월 소비자물가지수 발표. 1분기 물가 흐름 종합.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-05-13",
    title: "CPI (4월)",
    description: "4월 소비자물가지수 발표.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-06-10",
    title: "CPI (5월)",
    description: "5월 소비자물가지수 발표. FOMC 당일 발표로 시장 변동성 극대화.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-14",
    title: "CPI (6월)",
    description: "6월 소비자물가지수 발표. 상반기 물가 추세 확인.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-08-11",
    title: "CPI (7월)",
    description: "7월 소비자물가지수 발표.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-09-09",
    title: "CPI (8월)",
    description: "8월 소비자물가지수 발표. FOMC 1주일 전 발표로 중요.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-10-13",
    title: "CPI (9월)",
    description: "9월 소비자물가지수 발표. 3분기 물가 추세 확인.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-11-12",
    title: "CPI (10월)",
    description: "10월 소비자물가지수 발표.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-12-09",
    title: "CPI (11월)",
    description: "11월 소비자물가지수 발표. FOMC 당일 발표.",
    impact: "critical",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },

  // ── NFP (비농업 고용) ──
  {
    date: "2026-01-09",
    title: "비농업 고용 (12월)",
    description: "12월 비농업부문 고용자수, 실업률, 평균임금 발표. 노동시장 건전성 지표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-02-06",
    title: "비농업 고용 (1월)",
    description: "1월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-03-06",
    title: "비농업 고용 (2월)",
    description: "2월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-04-03",
    title: "비농업 고용 (3월)",
    description: "3월 비농업부문 고용 발표. 1분기 고용 마무리.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-05-01",
    title: "비농업 고용 (4월)",
    description: "4월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-06-05",
    title: "비농업 고용 (5월)",
    description: "5월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-10",
    title: "비농업 고용 (6월)",
    description: "6월 비농업부문 고용 발표. 7월 4일 연휴 영향으로 날짜 변경.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-08-07",
    title: "비농업 고용 (7월)",
    description: "7월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-09-04",
    title: "비농업 고용 (8월)",
    description: "8월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-10-02",
    title: "비농업 고용 (9월)",
    description: "9월 비농업부문 고용 발표. 3분기 고용 마무리.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-11-06",
    title: "비농업 고용 (10월)",
    description: "10월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-12-04",
    title: "비농업 고용 (11월)",
    description: "11월 비농업부문 고용 발표.",
    impact: "critical",
    category: "jobs",
    time: "08:30 ET",
    isEstimate: true,
  },

  // ── PCE (개인소비지출 물가) ──
  {
    date: "2026-01-30",
    title: "PCE 물가 (12월)",
    description: "연준이 선호하는 인플레이션 지표. 근원 PCE 전년비가 핵심.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-02-27",
    title: "PCE 물가 (1월)",
    description: "1월 PCE 물가 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-03-27",
    title: "PCE 물가 (2월)",
    description: "2월 PCE 물가 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-04-24",
    title: "PCE 물가 (3월)",
    description: "3월 PCE 물가 발표. 1분기 연준 선호 물가 지표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-05-29",
    title: "PCE 물가 (4월)",
    description: "4월 PCE 물가 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-06-26",
    title: "PCE 물가 (5월)",
    description: "5월 PCE 물가 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-31",
    title: "PCE 물가 (6월)",
    description: "6월 PCE 물가 발표. 상반기 연준 물가 목표 달성 여부 확인.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-08-28",
    title: "PCE 물가 (7월)",
    description: "7월 PCE 물가 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-09-25",
    title: "PCE 물가 (8월)",
    description: "8월 PCE 물가 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-10-30",
    title: "PCE 물가 (9월)",
    description: "9월 PCE 물가 발표. 3분기 물가 종합.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-11-25",
    title: "PCE 물가 (10월)",
    description: "10월 PCE 물가 발표. 추수감사절 전날 조기 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-12-23",
    title: "PCE 물가 (11월)",
    description: "11월 PCE 물가 발표.",
    impact: "high",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },

  // ── GDP 속보치 ──
  {
    date: "2026-01-29",
    title: "GDP 속보치 (Q4 2025)",
    description: "2025년 4분기 GDP 성장률 속보치 발표 (연율 환산).",
    impact: "high",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-04-29",
    title: "GDP 속보치 (Q1 2026)",
    description: "2026년 1분기 GDP 성장률 속보치 발표.",
    impact: "high",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-30",
    title: "GDP 속보치 (Q2 2026)",
    description: "2026년 2분기 GDP 성장률 속보치 발표. 상반기 경제 성장 종합.",
    impact: "high",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-10-29",
    title: "GDP 속보치 (Q3 2026)",
    description: "2026년 3분기 GDP 성장률 속보치 발표.",
    impact: "high",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },

  // ── PPI (생산자물가지수) ──
  {
    date: "2026-01-15",
    title: "PPI (12월)",
    description: "생산자물가지수 발표. CPI 선행 지표 역할.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-02-12",
    title: "PPI (1월)",
    description: "1월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-03-12",
    title: "PPI (2월)",
    description: "2월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-04-10",
    title: "PPI (3월)",
    description: "3월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-05-14",
    title: "PPI (4월)",
    description: "4월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-06-11",
    title: "PPI (5월)",
    description: "5월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-15",
    title: "PPI (6월)",
    description: "6월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-08-12",
    title: "PPI (7월)",
    description: "7월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-09-10",
    title: "PPI (8월)",
    description: "8월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-10-14",
    title: "PPI (9월)",
    description: "9월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-11-13",
    title: "PPI (10월)",
    description: "10월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-12-10",
    title: "PPI (11월)",
    description: "11월 생산자물가지수 발표.",
    impact: "medium",
    category: "inflation",
    time: "08:30 ET",
    isEstimate: true,
  },

  // ── 소매판매 ──
  {
    date: "2026-01-15",
    title: "소매판매 (12월)",
    description: "소비 지출 동향. 시즌 소비 마무리 확인.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-02-13",
    title: "소매판매 (1월)",
    description: "1월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-03-13",
    title: "소매판매 (2월)",
    description: "2월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-04-15",
    title: "소매판매 (3월)",
    description: "3월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-05-15",
    title: "소매판매 (4월)",
    description: "4월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-06-12",
    title: "소매판매 (5월)",
    description: "5월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-16",
    title: "소매판매 (6월)",
    description: "6월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-08-14",
    title: "소매판매 (7월)",
    description: "7월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-09-11",
    title: "소매판매 (8월)",
    description: "8월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-10-15",
    title: "소매판매 (9월)",
    description: "9월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-11-13",
    title: "소매판매 (10월)",
    description: "10월 소매판매 발표.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },
  {
    date: "2026-12-11",
    title: "소매판매 (11월)",
    description: "11월 소매판매 발표. 블랙프라이데이 소비 동향 포함.",
    impact: "medium",
    category: "growth",
    time: "08:30 ET",
    isEstimate: true,
  },

  // ── JOLTS (구인·이직 통계) ──
  {
    date: "2026-02-04",
    title: "JOLTS (12월)",
    description: "구인 건수, 해고율, 자발적 퇴직률 발표. 노동시장 수급 지표.",
    impact: "medium",
    category: "jobs",
    time: "10:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-03-04",
    title: "JOLTS (1월)",
    description: "1월 구인·이직 통계 발표.",
    impact: "medium",
    category: "jobs",
    time: "10:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-04-01",
    title: "JOLTS (2월)",
    description: "2월 구인·이직 통계 발표.",
    impact: "medium",
    category: "jobs",
    time: "10:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-05-05",
    title: "JOLTS (3월)",
    description: "3월 구인·이직 통계 발표.",
    impact: "medium",
    category: "jobs",
    time: "10:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-06-03",
    title: "JOLTS (4월)",
    description: "4월 구인·이직 통계 발표.",
    impact: "medium",
    category: "jobs",
    time: "10:00 ET",
    isEstimate: true,
  },
  {
    date: "2026-07-07",
    title: "JOLTS (5월)",
    description: "5월 구인·이직 통계 발표.",
    impact: "medium",
    category: "jobs",
    time: "10:00 ET",
    isEstimate: true,
  },

  // ── 실적 발표 시즌 (대형주) ──
  // Q4 2025 실적 (1-2월 2026)
  {
    date: "2026-01-22",
    title: "넷플릭스 실적 (Q4 2025)",
    description: "넷플릭스 4분기 실적 발표. 구독자 수 및 광고 매출 주목.",
    impact: "medium",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-01-28",
    title: "마이크로소프트·메타 실적 (Q4 2025)",
    description: "MSFT: Azure 클라우드, AI 코파일럿 성장률 주목. META: 광고 매출·AI 투자.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-01-29",
    title: "애플·테슬라 실적 (Q4 2025)",
    description: "AAPL: iPhone 판매량, 서비스 매출. TSLA: 인도량, 마진율.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-02-05",
    title: "알파벳·아마존 실적 (Q4 2025)",
    description: "GOOGL: 검색 광고·클라우드. AMZN: AWS 성장률, 물류 이익.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-02-26",
    title: "엔비디아 실적 (Q4 FY2026)",
    description: "데이터센터 GPU 수요, Blackwell 매출, AI 인프라 투자 동향.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },

  // Q1 2026 실적 (4-5월 2026)
  {
    date: "2026-04-14",
    title: "JP모건·웰스파고 실적 (Q1 2026)",
    description: "주요 은행 실적. 순이자마진, 대출 부실률, 투자은행 수수료.",
    impact: "medium",
    category: "earnings",
    time: "장 시작 전",
    isEstimate: true,
  },
  {
    date: "2026-04-22",
    title: "테슬라 실적 (Q1 2026)",
    description: "1분기 차량 인도량, 에너지 부문, FSD 수익화 현황.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-04-28",
    title: "마이크로소프트·메타 실적 (Q1 2026)",
    description: "MSFT Azure, META AI 광고 성장률 주목.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-04-30",
    title: "애플·아마존 실적 (Q1 2026)",
    description: "AAPL 서비스 매출, AMZN AWS 마진.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-05-07",
    title: "알파벳 실적 (Q1 2026)",
    description: "구글 검색 광고, YouTube, Google Cloud 성장률.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },
  {
    date: "2026-05-28",
    title: "엔비디아 실적 (Q1 FY2027)",
    description: "Blackwell GPU 출하, 데이터센터 수요, 중국 수출 규제 영향.",
    impact: "high",
    category: "earnings",
    time: "장 마감 후",
    isEstimate: true,
  },

  // ── 정책·거시 이벤트 ──
  {
    date: "2026-02-24",
    title: "잭슨홀 연설 (예상)",
    description: "캔자스시티 연준 연례 심포지엄. 연준 의장의 중장기 통화정책 방향 힌트.",
    impact: "high",
    category: "policy",
    isEstimate: true,
  },
  {
    date: "2026-07-01",
    title: "관세·무역 정책 검토",
    description: "미국 무역대표부(USTR) 연례 무역 정책 검토. 글로벌 공급망 및 관세 영향.",
    impact: "medium",
    category: "policy",
    isEstimate: true,
  },
];

export function getEventsByDate(date: string): EconomicEvent[] {
  return ECONOMIC_EVENTS.filter((e) => e.date === date).sort((a, b) => {
    const order: EventImpact[] = ["critical", "high", "medium", "low"];
    return order.indexOf(a.impact) - order.indexOf(b.impact);
  });
}

export function getEventsInMonth(year: number, month: number): EconomicEvent[] {
  const prefix = `${year}-${String(month + 1).padStart(2, "0")}`;
  return ECONOMIC_EVENTS.filter((e) => e.date.startsWith(prefix));
}
